name: Build and Publish current Resume

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current Resume
        uses: actions/checkout@v4
          
      - name: Compile Resume
        uses: xu-cheng/latex-action@v3
        with:
          root_file: mai-joel_maximilian-curriculum_vitae.tex
          # Add any additional configurations here, such as 'args' or 'extra_system_packages'
      
      - name: Test if Resume build was successful
        run: '(test -f mai-joel_maximilian-curriculum_vitae.pdf && echo PDF exists) || (echo PDF does not exist && exit 1)'
        
      - name: Get the current date and time
        id: date
        run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d-%H-%M')"

      - name: Generate Release Tag
        id: generate_tag
        run: echo "::set-output name=tag::v${{ steps.date.outputs.timestamp }}"
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        with:
          files: |
            downloads/mai-joel_maximilian-curriculum_vitae.pdf
          tag_name: ${{ steps.generate_tag.outputs.tag }}
          release_name: Release ${{ steps.generate_tag.outputs.tag }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Resume Asset to Release
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mai-joel_maximilian-curriculum_vitae.pdf
          asset_name: mai-joel_maximilian-curriculum_vitae.pdf
          asset_content_type: application/pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
