name: Build LaTeX Document and Move PDF

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LateX
        # You may pin to the exact commit or the version.
        # uses: vinay0410/tectonic-action@b3138021657a3cdb3823f3980be054ca89e86d81
        uses: vinay0410/tectonic-action@v1.1.2
        with:
          tex_path: 'mai-joel_maximilian-curriculum_vitae.tex' 
          push: yes

      - name: Rename and Move PDF
        run: |
          mv mai-joel_maximilian-curriculum_vitae.pdf downloads/
          
